name: LuaRocks Release
on:
  pull_request: # Will test a local install without uploading to luarocks.org
  workflow_dispatch:
jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7.2.0
        with:
          version: "0.3.0"
          license: "GPLv2"
          detailed_description: |
            Use which-key.nvim bindings to cycle between your colorschemes.
          dependencies: |
            which-key.nvim
          labels: |
            neovim
          copy_directories: |
            {{ neovim.plugin.dirs }}
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
