name: Action Release
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  merge_group:
    branches:
      - main
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build Project Assets
        run: |
          mkdir -pv which-colorscheme.nvim
          cp -rv lua README.md LICENSE Makefile which-colorscheme.nvim
          zip -r -9 which-colorscheme.nvim.zip which-colorscheme.nvim
          tar cvJf which-colorscheme.nvim.tar.xz which-colorscheme.nvim
          tar cvzf which-colorscheme.nvim.tar.gz which-colorscheme.nvim
          sha512sum which-colorscheme.nvim.zip which-colorscheme.nvim.tar.xz which-colorscheme.nvim.tar.gz >| sha512sums.txt
          md5sum which-colorscheme.nvim.zip which-colorscheme.nvim.tar.xz which-colorscheme.nvim.tar.gz >| md5sums.txt
          rm -rfv which-colorscheme.nvim
      - name: Get Release
        uses: joutvhu/get-release@v1.0.3
        with:
          latest: true
          prerelease: true
          pattern: '^v.*'
          debug: true
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release File
        run: |
          echo ${{ github.sha }} > Release.txt
          cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2.5.0
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            which-colorscheme.nvim.tar.gz
            which-colorscheme.nvim.tar.xz
            which-colorscheme.nvim.zip
            md5sums.txt
            sha512sums.txt
          token: ${{ secrets.GITHUB_TOKEN }}
